#!/bin/bash
while getopts p: option
do
case "${option}"
in
p) set -f # disable glob
   IFS=,  # split on space characters
   array=($OPTARG) ;; # use the split+glob operator
esac
done
echo "Number of arguments: ${#array[@]}"
for i in "${array[@]}";
do
    gcc -o main main.c
   ./main ${i}
    echo "${i},$?" >> result.csv
done